apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockubassignment-deployment
spec:
  selector:
    matchLabels:
      app: dockubassignment-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: dockubassignment-deployment
    spec:
      containers:
      - name: dockubassignment-deployment
        image: docker.io/sumit3571/doc_sumit3571:v1
        ports:
        - containerPort: 8991