apiVersion: v1
kind: Service
metadata:
  name: dockubassignment-service
spec:
  type: NodePort
  selector:
    app: dockubassignment-deployment
 
  ports:
  - port: 8991
    targetPort: 8991
    nodePort: 32005